//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group13SSIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyDetail
    {
        public int ApplyId { get; set; }
        public int StationeryId { get; set; }
        public int Quantity { get; set; }
    
        public virtual Apply Apply { get; set; }
        public virtual Stationery Stationery { get; set; }
    }
}
