//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group13SSIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisbursementDetail
    {
        public int DisbursementDetailId { get; set; }
        public int DisbursementId { get; set; }
        public int StationeryId { get; set; }
        public int NeededQty { get; set; }
        public Nullable<int> RetrievalQty { get; set; }
        public Nullable<int> DeliveryQty { get; set; }
        public string Comment { get; set; }
    }
}
