//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group13SSIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reorder
    {
        public int ReorderId { get; set; }
        public int SupplierId { get; set; }
        public int ClerkId { get; set; }
        public double Amount { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
    }
}
